In [172]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib
%matplotlib inline

In [85]:
data = pd.read_csv('titanic/train.csv')

In [89]:
Y = data["Survived"] 
X = data[["Pclass","Sex","Age","SibSp","Parch", "Fare"]]

In [113]:
missing_values = X.isnull()

In [91]:
print(sum(missing_values["Pclass"]))
print(sum(missing_values["Sex"]))
print(sum(missing_values["Age"]))
print(sum(missing_values["SibSp"]))
print(sum(missing_values["Parch"]))
print(sum(missing_values["Fare"]))

0
0
177
0
0
0

In [93]:
ages = [i for i in X["Age"] if str(i) != "nan"]
average = sum(ages)/len(ages)
average

29.69911764705882

In [159]:
fare = [i for i in X["Fare"] if str(i) != "nan"]
averageFare = sum(fare)/len(fare)
averageFare

0.06285842768394748

In [116]:
X["Age"] = X["Age"].fillna(average)
X["Sex"] = pd.get_dummies(X['Sex'], drop_first=True)
X["Age"] = X["Age"] / X["Age"].max()
X["Fare"] = X["Fare"] / X["Fare"].max()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [118]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=101)

In [119]:
logistic = LogisticRegression() #0.77
logistic.fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [120]:
logistic.score(X_test, y_test)

0.7835820895522388

In [126]:
data["Survived"].corr(X["Sex"])

-0.5433513806577556

In [165]:
data["Survived"].corr(X["Pclass"])

-0.3384810359610148

In [166]:
data["Survived"].corr(X["Age"])

-0.06980851528714312

In [167]:
data["Survived"].corr(X["SibSp"])

-0.03532249888573564

In [168]:
data["Survived"].corr(X["Parch"])

0.08162940708348371

In [169]:
data["Survived"].corr(X["Fare"])

0.25730652238496277

In [181]:
data["Embarked"] = pd.get_dummies(data['Embarked'], drop_first=True)

In [182]:
data["Survived"].corr(data["Embarked"])

0.003650382683971964

In [187]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,0

-----

In [147]:
test = pd.read_csv('titanic/test.csv')

In [148]:
X_test = test[["Pclass","Sex","Age","SibSp","Parch", "Fare"]]

In [160]:
X_test["Age"] = X_test["Age"].fillna(average)
X_test["Fare"] = X_test["Fare"].fillna(averageFare)
X_test["Sex"] = pd.get_dummies(X_test['Sex'], drop_first=True)
X_test["Age"] = X_test["Age"] / X_test["Age"].max()
X_test["Fare"] = X_test["Fare"] / X_test["Fare"].max()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [162]:
X_test

     Pclass  Sex       Age  SibSp  Parch      Fare
0         3    1  0.453947      0      0  0.015282
1         3    0  0.618421      1      0  0.013663
2         2    1  0.815789      0      0  0.018909
3         3    1  0.355263      0      0  0.016908
4         3    0  0.289474      1      1  0.023984
5         3    1  0.184211      0      0  0.018006
6         3    0  0.394737      0      0  0.014891
7         2    1  0.342105      1      1  0.056604
8         3    0  0.236842      0      0  0.014110
9         3    1  0.276316      2      0  0.047138
10        3    1  0.390778      0      0  0.015412
11        1    1  0.605263      0      0  0.050749
12        1    0  0.302632      1      0  0.160574
13        2    1  0.828947      1      0  0.050749
14        1    0  0.618421      1      0  0.119406
15        2    0  0.315789      1      0  0.054107
16        2    1  0.460526      0      0  0.024106
17        3    1  0.276316      0      0  0.014102
18        3    0  0.355263      1      0  0.015469
19        3    0  0.592105      0      0  0.014102
20        1    1  0.723684      1      0  0.115941
21        3    1  0.118421      0      1  0.006189
22        1    0  0.390778      0      0  0.061842
23        1    1  0.276316      0      1  0.119804
24        1    0  0.631579      1      3  0.512122
25        3    1  0.657895      1      0  0.028302
26        1    0  0.289474      0      1  0.120975
27        3    1  0.296053      0      0  0.014102
28        1    1  0.539474      0      0  0.059532
29        3    1  0.390778      2      0  0.042315
..      ...  ...       ...    ...    ...       ...
388       3    1  0.276316      0      0  0.015127
389       3    1  0.078947      3      1  0.041136
390       1    1  0.302632      0      0  0.182500
391       1    0  0.671053      0      1  0.076904
392       3    1  0.171053      0      2  0.039525
393       2    1  0.618421      0      0  0.020495
394       3    1  0.381579      3      1  0.042990
395       1    0  0.236842      1      0  0.117112
396       3    1  0.315789      0      0  0.014151
397       1    0  0.631579      1      1  0.154588
398       3    1  0.289474      0      0  0.015176
399       3    1  0.407895      0      0  0.015094
400       1    0  0.394737      0      0  0.321798
401       2    1  0.500000      1      0  0.040989
402       1    0  0.289474      0      1  0.115941
403       1    1  0.223684      0      0  0.091933
404       1    1  0.565789      1      0  0.054107
405       2    1  0.263158      0      0  0.027058
406       2    1  0.302632      1      0  0.020495
407       1    1  0.657895      1      1  0.412821
408       3    0  0.390778      0      0  0.015070
409       3    0  0.039474      1      1  0.026887
410       3    0  0.390778      0      0  0.015127
411       1    0  0.486842      1      0  0.175668
412       3    0  0.368421      0      0  0.015176
413       3    1  0.390778      0      0  0.015713
414       1    0  0.513158      0      0  0.212559
415       3    1  0.506579      0      0  0.014151
416       3    1  0.390778      0      0  0.015713
417       3    1  0.390778      1      1  0.043640

[418 rows x 6 columns]

In [163]:
logistic.predict(X_test)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])